[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
pheidippides-messenger = {path= "../../lib/pheidippides-messenger" }
pheidippides-web = {path= "../../lib/pheidippides-web" }
pheidippides-auth = { path = "../../lib/pheidippides-auth" }
web-server = {path = "../../lib/web-server"}
postgres-db = {path = "../../lib/postgres-db" }
mock-db = {path = "../../lib/mock-db" }

anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
tokio-util = "0.7.11"
