[workspace]
resolver = "2"
members = [
    "pheidippides",
    "pheidippides-utils",
    "web-server",
    "postgres-db",
    "mock-db",
    "tests",
    "bin/server",
    "bin/migrate", "pheidippides-db-tests",
]
