[package]
name = "pheidippides-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
chrono = "0.4.38"
serde = "1.0.202"
tokio = { version = "1.37.0", features = ["macros", "rt", "sync"] }
url-escape = "0.1.1"
uuid = "1.8.0"
