[package]
name = "mock-db"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
password-hash = "0.5.0"
pheidippides = { path="../pheidippides" }
uuid = "1.8.0"

[dev-dependencies]
tokio = "1.37.0"
pheidippides-db-tests = { path = "../pheidippides-db-tests" }
